//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GW2ExplorerCraftTool.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GW2ExplorerCraftTool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        /// </summary>
        public static System.Drawing.Icon _102465 {
            get {
                object obj = ResourceManager.GetObject("_102465", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Search.
        /// </summary>
        public static string ButtonSearchText {
            get {
                return ResourceManager.GetString("ButtonSearchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No.
        /// </summary>
        public static string ChangeLanguageMessageButtonNo {
            get {
                return ResourceManager.GetString("ChangeLanguageMessageButtonNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Yes.
        /// </summary>
        public static string ChangeLanguageMessageButtonYes {
            get {
                return ResourceManager.GetString("ChangeLanguageMessageButtonYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Changing the language will restart the application.
        ///Are you sure you want to change the language ?.
        /// </summary>
        public static string ChangeLanguageMessageContent {
            get {
                return ResourceManager.GetString("ChangeLanguageMessageContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Changing the language.
        /// </summary>
        public static string ChangeLanguageMessageTitle {
            get {
                return ResourceManager.GetString("ChangeLanguageMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Search also into ingredients.
        /// </summary>
        public static string CheckBoxSearchAlsoIngredients {
            get {
                return ResourceManager.GetString("CheckBoxSearchAlsoIngredients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show the known/checked recipes.
        /// </summary>
        public static string CheckBoxShowCheckRecipes {
            get {
                return ResourceManager.GetString("CheckBoxShowCheckRecipes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Disciplines....
        /// </summary>
        public static string ComboBoxDisciplineFirstEntry {
            get {
                return ResourceManager.GetString("ComboBoxDisciplineFirstEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rarities....
        /// </summary>
        public static string ComboBoxRarityFirstEntry {
            get {
                return ResourceManager.GetString("ComboBoxRarityFirstEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Types of recipe....
        /// </summary>
        public static string ComboBoxRecipeTypeFirstEntry {
            get {
                return ResourceManager.GetString("ComboBoxRecipeTypeFirstEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete.
        /// </summary>
        public static string DeleteRecipeInErrorMessageButtonDelete {
            get {
                return ResourceManager.GetString("DeleteRecipeInErrorMessageButtonDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do not delete.
        /// </summary>
        public static string DeleteRecipeInErrorMessageButtonNotDelete {
            get {
                return ResourceManager.GetString("DeleteRecipeInErrorMessageButtonNotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you want to delete and redownload the recipes in error ?.
        /// </summary>
        public static string DeleteRecipeInErrorMessageContent {
            get {
                return ResourceManager.GetString("DeleteRecipeInErrorMessageContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à recipe(s) in error.
        /// </summary>
        public static string DeleteRecipeInErrorMessageContentRecipesCount {
            get {
                return ResourceManager.GetString("DeleteRecipeInErrorMessageContentRecipesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Recipes in error.
        /// </summary>
        public static string DeleteRecipeInErrorMessageTitle {
            get {
                return ResourceManager.GetString("DeleteRecipeInErrorMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The max level must be an integer value!.
        /// </summary>
        public static string ErrorMessageMaxLevelMustBeAnIntValue {
            get {
                return ResourceManager.GetString("ErrorMessageMaxLevelMustBeAnIntValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The min level must be an integer value!.
        /// </summary>
        public static string ErrorMessageMinLevelMustBeAnIntValue {
            get {
                return ResourceManager.GetString("ErrorMessageMinLevelMustBeAnIntValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à http://www.gw2spidy.com/item/{0}.
        /// </summary>
        public static string Gw2SpidyItemHyperLinkUrlBase {
            get {
                return ResourceManager.GetString("Gw2SpidyItemHyperLinkUrlBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Infusion Slot.
        /// </summary>
        public static string InfusionSlotLabel {
            get {
                return ResourceManager.GetString("InfusionSlotLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Disciplines.
        /// </summary>
        public static string ItemDescriptionDisciplinesLabel {
            get {
                return ResourceManager.GetString("ItemDescriptionDisciplinesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Can be crafted!.
        /// </summary>
        public static string ItemDescriptionIsCraftableLabel {
            get {
                return ResourceManager.GetString("ItemDescriptionIsCraftableLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Required level.
        /// </summary>
        public static string ItemDescriptionRequiredLevelLabel {
            get {
                return ResourceManager.GetString("ItemDescriptionRequiredLevelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;FlowDocument xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///              ColumnWidth=&quot;400&quot; FontSize=&quot;14&quot; FontFamily=&quot;Georgia&quot;&gt;
        ///    &lt;Paragraph&gt;
        ///        Bienvenue sur GW2 Crafter - My Recipes finder.
        ///    &lt;/Paragraph&gt;
        ///    &lt;Paragraph&gt;
        ///        What is this fucking tool ?
        ///Mon objectif en créant cet outil était d&apos;avoir sous la main la liste complète des recettes, et de pouvoir rechercher celles que je ne connaissais pas in-game.
        ///        L&apos;idée était surtout de pouvoir les éliminer de c [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string RichTextBoxWelcomeText {
            get {
                return ResourceManager.GetString("RichTextBoxWelcomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Something goes wrong with download. Please try later!.
        /// </summary>
        public static string SomethingIsWrongNoDownloadPossible {
            get {
                return ResourceManager.GetString("SomethingIsWrongNoDownloadPossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Something is wrong with this ingredient!.
        /// </summary>
        public static string SomethingIsWrongWithThisIngredient {
            get {
                return ResourceManager.GetString("SomethingIsWrongWithThisIngredient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Something is wrong with this recipe!.
        /// </summary>
        public static string SomethingIsWrongWithThisRecipe {
            get {
                return ResourceManager.GetString("SomethingIsWrongWithThisRecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Downloaded recipes: {0}.
        /// </summary>
        public static string TextBoxCachedRecipes {
            get {
                return ResourceManager.GetString("TextBoxCachedRecipes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Checking recipes in error....
        /// </summary>
        public static string TextBoxCheckingRecipesInError {
            get {
                return ResourceManager.GetString("TextBoxCheckingRecipesInError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Download finished..
        /// </summary>
        public static string TextBoxCurrentDownloadFinished {
            get {
                return ResourceManager.GetString("TextBoxCurrentDownloadFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Download in progress... {0}/{1} - {2:P2} - {3:D2}:{4:D2}.
        /// </summary>
        public static string TextBoxCurrentDownloadInProgress {
            get {
                return ResourceManager.GetString("TextBoxCurrentDownloadInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Loading cached recipes. Please wait....
        /// </summary>
        public static string TextBoxCurrentDownloadLoadingCachedRecipes {
            get {
                return ResourceManager.GetString("TextBoxCurrentDownloadLoadingCachedRecipes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No Internet connection available!.
        /// </summary>
        public static string TextBoxCurrentDownloadNetworkNotAvailableNotification {
            get {
                return ResourceManager.GetString("TextBoxCurrentDownloadNetworkNotAvailableNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} recipe(s) to download. Please wait....
        /// </summary>
        public static string TextBoxCurrentDownloadNewRecipesFoundNotification {
            get {
                return ResourceManager.GetString("TextBoxCurrentDownloadNewRecipesFoundNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No new recipe found..
        /// </summary>
        public static string TextBoxCurrentDownloadNoNewRecipesFoundNotification {
            get {
                return ResourceManager.GetString("TextBoxCurrentDownloadNoNewRecipesFoundNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ouch, something goes wrong!.
        /// </summary>
        public static string TextBoxCurrentDownloadSomethingGoesWrong {
            get {
                return ResourceManager.GetString("TextBoxCurrentDownloadSomethingGoesWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Search for new recipes....
        /// </summary>
        public static string TextBoxCurrentDownloadStarting {
            get {
                return ResourceManager.GetString("TextBoxCurrentDownloadStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Level.
        /// </summary>
        public static string TextBoxLevelLabel {
            get {
                return ResourceManager.GetString("TextBoxLevelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Found recipes : {0} ({1} checked recipes).
        /// </summary>
        public static string TextBoxSearchResult {
            get {
                return ResourceManager.GetString("TextBoxSearchResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please, you need to set some parameters to search for the recipes!.
        /// </summary>
        public static string TextBoxSearchResultAlterIfNoParameter {
            get {
                return ResourceManager.GetString("TextBoxSearchResultAlterIfNoParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You can search for recipes..
        /// </summary>
        public static string TextBoxSearchResultDefaultText {
            get {
                return ResourceManager.GetString("TextBoxSearchResultDefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Search in progress....
        /// </summary>
        public static string TextBoxSearchResultInProgress {
            get {
                return ResourceManager.GetString("TextBoxSearchResultInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show latest download.
        /// </summary>
        public static string TextBoxShowMeLatestDownloadedRecipes {
            get {
                return ResourceManager.GetString("TextBoxShowMeLatestDownloadedRecipes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show me the recipes in error.
        /// </summary>
        public static string TextBoxShowMeRecipesInError {
            get {
                return ResourceManager.GetString("TextBoxShowMeRecipesInError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Buy Price:.
        /// </summary>
        public static string TextBoxTradingPostDataBuyPriceLabel {
            get {
                return ResourceManager.GetString("TextBoxTradingPostDataBuyPriceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Demand:.
        /// </summary>
        public static string TextBoxTradingPostDataDemandLabel {
            get {
                return ResourceManager.GetString("TextBoxTradingPostDataDemandLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No data found!.
        /// </summary>
        public static string TextBoxTradingPostDataNoDataFound {
            get {
                return ResourceManager.GetString("TextBoxTradingPostDataNoDataFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sell Price:.
        /// </summary>
        public static string TextBoxTradingPostDataSellPriceLabel {
            get {
                return ResourceManager.GetString("TextBoxTradingPostDataSellPriceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supply:.
        /// </summary>
        public static string TextBoxTradingPostDataSupplyLabel {
            get {
                return ResourceManager.GetString("TextBoxTradingPostDataSupplyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à http://wiki.guildwars2.com/wiki/{0}.
        /// </summary>
        public static string WikiHyperLinkUrlBase {
            get {
                return ResourceManager.GetString("WikiHyperLinkUrlBase", resourceCulture);
            }
        }
    }
}
